name: deploy

on: pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm ci
      - run: npm run build
      - name: deploy
        uses: easingthemes/ssh-deploy@3884c8554ff45c0fd37d3f12a76288d06ce7a2ff # v.4.1.8
        env:
          SOURCE: public/
          TARGET: ~/public_html/new/
          SCRIPT_BEFORE: ls -la
          REMOTE_HOST: ${{ vars.DEPLOY_HOST }}
          REMOTE_PORT: ${{ vars.DEPLOY_PORT }}
          REMOTE_USER: ${{ vars.DEPLOY_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
