name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
  repository_dispatch:
    types: [cms-publish]

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm ci
      - run: npm run build
        env:
          CONTENTFUL_SPACE_ID: ${{ vars.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ENV: ${{ vars.CONTENTFUL_ENV }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
      - name: deploy
        uses: easingthemes/ssh-deploy@aa1c48118d8dc380d98fcec25cb4ea6da39029ba # v.4.1.10
        env:
          SOURCE: public/
          TARGET: ~/public_html/
          ARGS: -rlgoDzvc -i --delete --exclude=.htaccess --exclude=404.html --exclude=tour.mp4 --exclude=fonts/ --exclude=.well-known/ --exclude=cgi-bin/
          REMOTE_HOST: ${{ vars.DEPLOY_HOST }}
          REMOTE_PORT: ${{ vars.DEPLOY_PORT }}
          REMOTE_USER: ${{ vars.DEPLOY_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
