name: end-to-end tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm
      - uses: cypress-io/github-action@a6333aaab4c95a31b3b020b33e00fe44d4af9f6e # v6.1.0
        with:
          build: npm run build
          start: npm run serve
          record: true
        env:
          CONTENTFUL_SPACE_ID: ${{ vars.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ENV: ${{ vars.CONTENTFUL_ENV }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
          COMMIT_INFO_SHA: ${{ github.event.pull_request.head.sha }}
